name: Project CI/CDeez nuts

on:
    push:
        branches: [rewrite]

jobs:
    build:
        strategy:
            matrix: 
                os: ["ubuntu-latest"]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Setup V
              uses: vlang/setup-v@v1
              with:
                check-latest: true
                
            - name: Install dependecies
              run: |
                sudo apt-get update
                sudo apt-get install --quiet -y libgc-dev
                sudo apt-get install --quiet -y libfreetype6-dev  libxi-dev libxcursor-dev libgl-dev
                
            - name: Install BASS
              run: |
                sudo wget https://github.com/Wieku/danser-go/raw/master/libbass.so -O /usr/lib/libbass.so
                sudo wget https://github.com/Wieku/danser-go/raw/master/libbass_fx.so -O /usr/lib/libbass_fx.so
                sudo wget https://raw.githubusercontent.com/Wieku/danser-go/master/framework/bass/bass.h /usr/include/bass.h
                sudo wget https://raw.githubusercontent.com/Wieku/danser-go/master/framework/bass/bass_fx.h /usr/include/bass_fx.h
            
            - name: Checkout ${{ github.event.repository.name }}
              uses: actions/checkout@v2

            - name: Build ${{ github.event.repository.name }}
              run: v shader assets/shaders/slider.glsl && v -cc gcc -gc boehm .
                

        
        

