# Derived from: https://github.com/vlang/vls/blob/use-tree-sitter/.github/workflows/prerelease.yml
name: Compile Kurarin

on:
  push:
    branches:
      - dev

jobs:
  build-windows-x64:
    runs-on: windows-2019
    timeout-minutes: 30
    env:
      VFLAGS: -cc gcc
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout kurarin
        uses: actions/checkout@v2
        with:
          path: kurarin
      - name: Build local V
        run: .\make.bat -gcc
      - name: Compile kurarin for Windows
        run: |
          cd kurarin
          ..\v.exe -cg -o kurarin_win_x64.exe .
      - name: Create binary only artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows_x64
          path: ./kurarin/kurarin_win_x64.exe

  
