# Derived from: https://github.com/vlang/vls/blob/use-tree-sitter/.github/workflows/prerelease.yml
name: Compile Kurarin

on:
  push:
    branches:
      - dev

jobs:
  build-windows-x64:
    runs-on: windows-2019
    timeout-minutes: 30
    env:
      VFLAGS: -cc gcc
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout kurarin
        uses: actions/checkout@v2
        with:
          path: kurarin
      - name: Build local V
        run: .\make.bat -gcc
      - name: Compile kurarin for Windows
        run: |
          cd kurarin
          ..\v.exe -cg -o kurarin_win_x64.exe .
      - name: Set up assets and shit
        run: |
          cd kurarin
          echo Setting Up Folders
          mkdir kurarin_release
          move assets kurarin_release/assets
          move kurarin_win_x64.exe kurarin_release
          echo Deleting useless stuff
          cd kurarin_release
          rm assets/screenshots -r
          rm assets/*.png
      - name: Upload the thing
        uses: actions/upload-artifact@v2
        with:
          name: windows_x64
          path: ./kurarin/kurarin_release
          
  pre-release:
    name: Release workflow builds
    needs: [build-windows-x64]
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch windows_x64
        uses: actions/download-artifact@v1
        with:
          name: windows_x64
          path: ./windows_x64
      - name: Zip the whole thing
        run: zip -r "kurarin_win64.zip" ./windows_x64
      - uses: "marvinpinto/action-automatic-releases@latest"
        name: Create Release and Upload Assets
        id: create_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Development Build"
          files: |
            kurarin_win64.zip

  
