# Derived from: https://github.com/vlang/vls/blob/use-tree-sitter/.github/workflows/prerelease.yml
name: Compile Kurarin

on:
  push:
    branches:
      - dev

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      VFLAGS: -cg -cc gcc
    steps:
      - name: Install Boehm GC
        run: sudo apt-get install libgc-dev
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout Kurarin
        uses: actions/checkout@v2
        with:
          path: kurarin
      - name: Build local V
        run: make && sudo ./v symlink
      - name: Compile Kurarin
        run: |
          cd kurarin
          v -o kurarin_linux .
      - name: Create binary only artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux_x64
          path: ./kurarin/kurarin_linux

  
